define(function() {
	var options = {
		jpg: {
			animAutoCrop: true,
			animAutoDifference: true,
			applyScale: false,
			colorMode: "24 bit",
			crop: false,
			cropBottom: 0,
			cropLeft: 0,
			cropRight: 0,
			cropTop: 0,
			ditherMode: "none",
			ditherPercent: 100,
			exportFormat: "JPEG",
			frameInfo: [],
			interlacedGIF: false,
			jpegQuality: 80,
			jpegSelPreserveButtons: false,
			jpegSelPreserveText: true,
			jpegSelQuality: 90,
			jpegSelQualityEnabled: false,
			jpegSmoothness: 0,
			jpegSubsampling: 0,
			localAdaptive: true,
			lossyGifAmount: 0,
			macCreator: "????",
			macFileType: "????",
			name: "JPEG - Better Quality",
			numCustomEntries: 0,
			numEntriesRequested: 0,
			numGridEntries: 6,
			optimized: true,
			paletteEntries: undefined,
			paletteInfo: undefined,
			paletteMode: "adaptive",
			paletteTransparency: "none",
			percentScale: 100,
			progressiveJPEG: false,
			savedAnimationRepeat: 0,
			sorting: "none",
			useScale: true,
			webSnapAdaptive: false,
			webSnapTolerance: 14,
			xSize: 0,
			ySize: 0
		},
		gif: {
			animAutoCrop: true,
			animAutoDifference: true,
			applyScale: false,
			colorMode: "indexed",
			crop: false,
			cropBottom: 0,
			cropLeft: 0,
			cropRight: 0,
			cropTop: 0,
			ditherMode: "none",
			ditherPercent: 100,
			exportFormat: "GIF",
			frameInfo: [],
			interlacedGIF: false,
			jpegQuality: 80,
			jpegSelPreserveButtons: false,
			jpegSelPreserveText: true,
			jpegSelQuality: 90,
			jpegSelQualityEnabled: false,
			jpegSmoothness: 0,
			jpegSubsampling: 0,
			localAdaptive: true,
			lossyGifAmount: 0,
			macCreator: "????",
			macFileType: "????",
			name: "GIF Adaptive 256",
			numCustomEntries: 0,
			numEntriesRequested: 256,
			numGridEntries: 6,
			optimized: true,
			paletteEntries: undefined,
			paletteInfo: undefined,
			paletteMode: "adaptive",
			paletteTransparency: "index alpha",
			percentScale: 100,
			progressiveJPEG: false,
			savedAnimationRepeat: 0,
			sorting: "none",
			useScale: true,
			webSnapAdaptive: false,
			webSnapTolerance: 14,
			xSize: 0,
			ySize: 0
		},
		png: {
			animAutoCrop: true,
			animAutoDifference: true,
			applyScale: false,
			colorMode: "32 bit",
			crop: false,
			cropBottom: 0,
			cropLeft: 0,
			cropRight: 0,
			cropTop: 0,
			ditherMode: "none",
			ditherPercent: 100,
			exportFormat: "PNG",
			frameInfo: [],
			interlacedGIF: false,
			jpegQuality: 80,
			jpegSelPreserveButtons: false,
			jpegSelPreserveText: true,
			jpegSelQuality: 90,
			jpegSelQualityEnabled: false,
			jpegSmoothness: 0,
			jpegSubsampling: 0,
			localAdaptive: true,
			lossyGifAmount: 0,
			macCreator: "????",
			macFileType: "????",
			name: "PNG32",
			numCustomEntries: 0,
			numEntriesRequested: 0,
			numGridEntries: 6,
			optimized: true,
			paletteEntries: undefined,
			paletteInfo: undefined,
			paletteMode: "adaptive",
			paletteTransparency: "none",
			percentScale: 100,
			progressiveJPEG: false,
			savedAnimationRepeat: 0,
			sorting: "none",
			useScale: true,
			webSnapAdaptive: false,
			webSnapTolerance: 14,
			xSize: 0,
			ySize: 0
		}
	};

	options.jpeg = options.jpg;

	return options;
});
